### ISSUE TITLE
Reputation object - parent categories

### ISSUE THREAD

**Issue by skhademcis** [ocsf/ocsf-schema#247]
Is it necessary to have parent category urls in reputation objects?  If so we need to have additional corresponding parent category ids with enumerated types

**Comment by Aniak5** [comment]
Good point @skhademcis , this is redundant information.

**Comment by Aniak5** [comment]
@rroupski and I also noticed that the reputation profile is used redundantly within the endpoint/url/tls and network event classes. This will be cleaned up so that we only see one `reputation` profile per class. We also decided to create a separate `domain_reputation` profile class to reduce redundancy.
