### ISSUE TITLE
Add reference to Objects in the Scan Class 

### ISSUE THREAD

**Issue by Noafr** [ocsf/ocsf-schema#255]
The Scan Class currently supports integers representing the number of scanned files/folders/network items but not a reference to the object themselves. For example, the Sha1 & path of a scanned file.

**Comment by rroupski** [comment]
The scan events report summary information only. This was an intentional design choice for the following reasons:

1.  avoid events that may have unlimited size, the number of scanned files could be rather large.
2. use the activity events to reports the same/similar issues, for example a virus detected in a file.

To link the scan to activity events, one can use `metadata.correlation_uid` attribute. For example,  `scan-event:metadata.correlation_uid = file-activity-event:metadata.correlation_uid`.

**Comment by tankbusta** [comment]
I do agree with @rroupski here that if there was an array of objects indicating which files were scanned, that would create a fairly large event. 

Since there's a way forward with @rroupski's suggestion, I'm going to close this but feel free to start a discussion if necessary
