### ISSUE TITLE
Add a Windows profile

### ISSUE THREAD

**Issue by mr-splunk** [ocsf/ocsf-schema#428]
In the System Activity workstreams sync, it's been brought up several times to get us closer towards platform-specific profiles (windows, linux, mac). Since there is growing need for a Windows profile, we should create one. Attribute considerations: windows event code, and windows object.

**Comment by pagbabian-splunk** [comment]
IMO the Windows profile is an instance of a platform profile, which seemed to have consensus of a few members.  We have a `win_resource` object for specific Windows kernel (or mostly kernel) resources which should be part of a Windows profile, as well as the Windows event code, something that has found its way into many analysis systems due to its prevalence.
The Windows profile can be then added to System Activity classes, e.g. Kernel Activity or Kernel Extension Activity (BTW, that latter object is a synonym for `File` as of now - it could be replaced with `File` or if it other things besides `File` in the future, it could be replaced by `win_resource`.
