### ISSUE TITLE
[ Schema ] MITRE ATT&CK Representation: Plural “Attacks”

### ISSUE THREAD

**Issue by dfirence** [ocsf/ocsf-schema#717]
Is the `Security Controls` and its `attacks` Object final?

Can this be be renamed to `mitre` where the array of the techniques lives under?

 It was confusing to want to see an `attacks` object I thought was how I would group telemetry of attacks (telemetry),   and upon closer look, I realized that’s just the array of `mitre semantics.

Ref: https://schema.ocsf.io/1.0.0-rc.3/objects/attack

**Comment by pagbabian-splunk** [comment]
`attacks` is an array of `attack` objects.  `Security Controls` is a profile that includes `attacks`.  They are both part of 1.0 and that sense, 'final.'

We are thinking that the `Attack` object itself is missing sub-techniques, so that is one area that could be improved.

We don't want an attribute named 'mitre' as that is the name of the organization, (and also, for example MITRE has D3FEND as well as ATT&CK).

**Comment by dfirence** [comment]
Thanks Paul, that makes sense for a schema, one final question.  Why is the Tactics and array and coupled with a single technique object?

**Comment by pagbabian-splunk** [comment]
The way we did it, for simplicity in not have arrays of arrays, is that the `attacks` attribute holds one Technique/Tactic pair per element of the `attacks` array.  If a Tactic has more than one Technique reported, then the Tactic would be repeated with different Techniques.  We might have to do something similar if we implement sub-techniques.  Mainly we are judicious with deeply nested arrays if possible.

**Comment by dfirence** [comment]
Thank you, @pagbabian-splunk .
