### ISSUE TITLE
schema.ocsf.io is down

### ISSUE THREAD

**Issue by maxabaumgarten** [ocsf/ocsf-schema#784]
[schema.ocsf.io](https://schema.ocsf.io/) is not working.

**Comment by mr-splunk** [comment]
The server is back up.

The root problem was that the server was running with a `t3.micro` AWS EC2 instance, and the CPU was getting pegged.
We are guessing this was caused by excessive event validations. This is fine, but we may want / need to add throttling eventually.
The solution was to bump up the instance type to `t3.medium`.
We also updated the OS software on this instance.

We captured the server's logs for post-mortem analysis - though, it's a shame those logs aren't in OCSF format 😜
