### ISSUE TITLE
Wrong version in the 1.0.0 packaged releases

### ISSUE THREAD

**Issue by k2niner** [ocsf/ocsf-schema#793]
Releases here: https://github.com/ocsf/ocsf-schema/releases/tag/v1.0.0

contain the following version.json:

```
{
  "version": "1.0.0-rc.3"
}
```

**Comment by mikeradka** [comment]
Nice catch here, @k2niner. Thanks for bringing it up in our sync yesterday. I don't *think* it is breaking for the creation of OCSF documents, but it may cause an issue when building a v1 server and could theoretically cause downstream issues for anyone utilizing that file.

@rmouritzen-splunk I looked at this a little bit, but am unsure of the best course of action. Since a tag is just a commit, I don't think it is as easy as just updating the version. If i understand, this could be immutable.

**Comment by mikeradka** [comment]
I looked at this once more. Perhaps there is still a way to approach this. I *think* we may be able to delete the old v1 tag, since there is also a v1 branch. The v1 branch indeed has the correct `version.json`.

**Comment by mikeradka** [comment]
The v1 release has been tested, verified, and updated. Here is the link: https://github.com/ocsf/ocsf-schema/releases/tag/v1.0.0
