### ISSUE TITLE
Remove "Status Code" from Vulerability Findings Class

### ISSUE THREAD

**Issue by sfriedfertig** [ocsf/ocsf-schema#829]
Self-explanatory. Not relevant to vulns.

**Comment by floydtree** [comment]
Leaving a summary of the discussion on the Weekly Call - We cannot really remove status_code from the vuln class today, since that field is inherited from the base_event which forms the basis of every single class in OCSF.

One of the potential solutions to this can be to add a new "disabled" boolean flag to the schema definition where inherited fields can be optionally disabled. Tagging @rmouritzen-splunk for visibility
