### ISSUE TITLE
'customer_uid' is unreferenced. Add to metadata object

### ISSUE THREAD

**Issue by mikeradka** [ocsf/ocsf-schema#833]
The `customer_uid` attribute is in the dictionary. It is currently unused but it is intended to represent a tenant or customer.  Splunk uses this in its metadata extension, but there are other OCSF partners wanting to use it as well. Thus, we believe it should be part of the Core schema.

<img width="1048" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/7a04e60d-52f1-41d3-9694-aeef3ac4bed3">

**Comment by sunilamin** [comment]
If we orientate from the view of the OCSF event collector (e.g. a SIEM) then I interpret the description for `metadata.customer_uid` to represents the concept of customer _in the SIEM_.

@mikeradka - Do you concur?

If that is the case, it is not what I'm looking for. I am looking to identify the tenant in a multi-tenant, SaaS product that is the _source_ of event. E.g. an EDR. This allow us to collect from multiple tenants from the source product.

I think a better place for this would be somewhere in `metadata.product` perhaps `metadata.product.tenant_id`.

**Comment by mikeradka** [comment]
That's an interesting perspective, @sunilamin . I think the `metadata.customer_uid` in its initial adoption was more geared towards the customer/tenant *for* a service provider utilizing OCSF. For instance, Splunk has customers/tenants in our product line and add this data to our OCSF events.

**Comment by rmouritzen-splunk** [comment]
@pagbabian-splunk, you are suggesting adding both `metadata.customer_uid` _and_ `metadata.product.customer_uid`? That makes sense to me. They would both be **Optional** fields, thus a safe, backwards compatible change.

**Comment by taddhar** [comment]
Just to put my interventions in writing, I considered 2 use cases in mind:

a) Compliancy and audit issues
b) Sophistication of customers

On a) I've seen all sorts of horror stories, e.g. customer tenants being merged with other customers data by mistakes. I let you imagine the GDPR issues and notifications required. So we may need to have a lot of precision regarding this attribute or at least enough documentation language as recommendations.

On b) the reason why a customer object may make sense is because of several issues (non exhaustive, not sorted):

- large customers can be super complex with their own IT division acting as an internal service provider and so the notion of 'customer' means internal entities, or even more complex when you have specific aggregates of customers e.g. governments or institutions (won't go in the sophistication of an object like the United Nations)
- large customers have many subsidiaries and world wide which asks the question how do we connect customer_uid A with customers_uid B, think for example when dealing with a large attack campaign
- service providers and then comes the concept of tiering: I am a large telco but I rely on a network of partners each of which has not only its own customers but as a large telco I can act on X, Y, Z (for example covers all infrastructure aspects) but the tier 2 service provider can act on specific aspects of security product A, B, C and the final customer only deals with its events and its policies
- etc.

These considerations do not mean that we should change anything but have we theoretically tested our approach against these use cases?

**Comment by mikeradka** [comment]
@pagbabian-splunk @taddhar to both of your points here and in #835 (and I'm open to more discussion on this if need be), do we think it could be adequate to add `customer_uid` and `customer_name` for now, and if later down the line there is appetite to also have those attributes in `metadata.object`, then add when needed? Or would we rather have some further discussion on whether there is opportunity for a `customer` object which could be applied to both `metadata` and `metadata.product`, to satisfy both cases presented?

**Comment by sunilamin** [comment]
@taddhar - Great summary of some of the complexities I have also seen in customer environments. I think that's why I tend to think in terms of concrete "tenants" in a SaaS system rather than the somewhat abstract notion of "customer". That's why I suggest the use of `metadata.product.tenant_uid`. However, I'm ok with using `customer_uid` if that fits better with an intended naming convention.

@mikeradka I don't think we need a whole `customer` object. However, I do need to be able to identify the tenant in the product. So `metadata.product.customer_uid` is what I'm looking for.

**Comment by mikeradka** [comment]
Hi @sunilamin and @taddhar, this was discussed a bit in today's weekly call. In order to get the ball rolling, we are going to proceed with baby steps

- Since we know that `customer_uid` is currently unused, we are going to bring it in to `metadata`, most likely with the new name of `tenant_uid`
- In doing so, we are going to look into refining the definition to ensure it can be applied across different use cases
- If it turns out that there is a specific need for another field, we can address it in a subsequent PR, but will need some data to see a scenario where using `metadata.tenant_uid` would be insufficient.

**Comment by mikeradka** [comment]
Closing this out since it was merged via #835. If there is some need down the line for a separate field, we could revisit in a new issue.
