### ISSUE TITLE
Schema Extension Versions

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-schema#869]
In the `metadata.extensions` object, all 3 name, uid and version are required. However, for the OCSF defined platform extensions Linux, macOS, Windows we haven't defined version in the json definition files. From a mapper's perspective, I do not have the information that can be used to populated the "required" fields in extension object. 

We need to explicitly add versions for these extensions. I recommend we maintain versions for native extensions and the core schema in sync, which would be `1.1.0-dev` as of today. But happy to discuss further.

Also, it appears we have not updated the [extension registry](https://github.com/ocsf/ocsf-schema/blob/main/extensions.md) with details about these native extensions.

**Comment by mikeradka** [comment]
We discussed this a bit in Tuesday's OCSF call. 

There was some talk of whether that field should be downgraded, and we determined it is better to keep it required. We can more easily just keep these 'first-class' extensions up-to-date in line with OCSF core's version. Alan confirmed that we could utilize metaschema to have some protection on ensuring these extension file versions are updated in accordance with core version updates.

It wasn't clear to many folks whether the extension `version` represented the version of the extension, or the version with which the extension is compatible. Since `version` represents the extension version, one thing that the team agreed on is the usefulness of adding an attribute that reflects the compatible ocsf version(s).

@jp-harvey may have some extra context to give here as well
